using LolZ.Model;
using System;
using System.Collections.Generic;
using System.Text;
using LolZ.Utilities;

namespace LolZ.Utilities
{
    public class ChampionNames
    {
        public static string ChampionNamesAccordingToChampionId()
        {
            string result;
            switch(Constants.ChampionId)
            {
                case 266: result = "Aatrox"; break;
                case 412: result = "Thresh"; break;
                case 23: result = "Tryndamere"; break;
                case 79: result = "Gragas"; break;
                case 69: result = "Cassiopeia"; break;
                case 136: result = "Aurelion Sol"; break;
                case 13: result = "Ryze"; break;
                case 78: result = "Poppy"; break;
                case 14: result = "Sion"; break;
                case 1: result = "Annie"; break;
                case 202: result = "Jhin"; break;
                case 43: result = "Karma"; break;
                case 111: result = "Nautilus"; break;
                case 240: result = "Kled"; break;
                case 99: result = "Lux"; break;
                case 103: result = "Ahri"; break;
                case 2: result = "Olaf"; break;
                case 112: result = "Viktor"; break;
                case 34: result = "Anivia"; break;
                case 27: result = "Singed"; break;
                case 86: result = "Garen"; break;
                case 127: result = "Lissandra"; break;
                case 57: result = "Maokai"; break;
                case 25: result = "Morgana"; break;
                case 28: result = "Evelynn"; break;
                case 105: result = "Fizz"; break;
                case 74: result = "Heimerdinger"; break;
                case 238: result = "Zed"; break;
                case 68: result = "Rumble"; break;
                case 82: result = "Mordekaiser"; break;
                case 37: result = "Sona"; break;
                case 96: result = "Kog'Maw"; break;
                case 55: result = "Katarina"; break;
                case 117: result = "Lulu"; break;
                case 22: result = "Ashe"; break;
                case 30: result = "Karthus"; break;
                case 12: result = "Alistar"; break;
                case 122: result = "Darius"; break;
                case 67: result = "Vayne"; break;
                case 110: result = "Varus"; break;
                case 77: result = "Udyr"; break;
                case 89: result = "Leona"; break;
                case 126: result = "Jayce"; break;
                case 134: result = "Syndra"; break;
                case 80: result = "Pantheon"; break;
                case 92: result = "Riven"; break;
                case 121: result = "Kha'Zix"; break;
                case 42: result = "Corki"; break;
                case 268: result = "Azir"; break;
                case 51: result = "Caitlyn"; break;
                case 76: result = "Nidalee"; break;
                case 85: result = "Kennen"; break;
                case 3: result = "Galio"; break;
                case 45: result = "Veigar"; break;
                case 432: result = "Bard"; break;
                case 150: result = "Gnar"; break;
                case 90: result = "Malzahar"; break;
                case 104: result = "Graves"; break;
                case 254: result = "Vi"; break;
                case 10: result = "Kayle"; break;
                case 39: result = "Irelia"; break;
                case 64: result = "Lee Sin"; break;
                case 420: result = "Illaoi"; break;
                case 60: result = "Elise"; break;
                case 106: result = "Volibear"; break;
                case 20: result = "Nunu"; break;
                case 4: result = "Twisted Fate"; break;
                case 24: result = "Jax"; break;
                case 102: result = "Shyvana"; break;
                case 429: result = "Kalista"; break;
                case 36: result = "Dr. Mundo"; break;
                case 427: result = "Ivern"; break;
                case 131: result = "Diana"; break;
                case 223: result = "Tahm Kench"; break;
                case 63: result = "Brand"; break;
                case 113: result = "Sejuani"; break;
                case 8: result = "Vladimir"; break;
                case 154: result = "Zac"; break;
                case 421: result = "Rek'Sai"; break;
                case 133: result = "Quinn"; break;
                case 84: result = "Akali"; break;
                case 163: result = "Taliyah"; break;
                case 18: result = "Tristana"; break;
                case 120: result = "Hecarim"; break;
                case 15: result = "Sivir"; break;
                case 236: result = "Lucian"; break;
                case 107: result = "Rengar"; break;
                case 19: result = "Warwick"; break;
                case 72: result = "Skarner"; break;
                case 54: result = "Malphite"; break;
                case 157: result = "Yasuo"; break;
                case 101: result = "Xerath"; break;
                case 17: result = "Teemo"; break;
                case 75: result = "Nasus"; break;
                case 58: result = "Renekton"; break;
                case 119: result = "Draven"; break;
                case 35: result = "Shaco"; break;
                case 50: result = "Swain"; break;
                case 91: result = "Talon"; break;
                case 40: result = "Janna"; break;
                case 115: result = "Ziggs"; break;
                case 245: result = "Ekko"; break;
                case 61: result = "Orianna"; break;
                case 114: result = "Fiora"; break;
                case 9: result = "Fiddlesticks"; break;
                case 31: result = "Cho'Gath"; break;
                case 33: result = "Rammus"; break;
                case 7: result = "LeBlanc"; break;
                case 16: result = "Soraka"; break;
                case 26: result = "Zilean"; break;
                case 56: result = "Nocturne"; break;
                case 222: result = "Jinx"; break;
                case 83: result = "Yorick"; break;
                case 6: result = "Urgot"; break;
                case 203: result = "Kindred"; break;
                case 21: result = "Miss Fortune"; break;
                case 62: result = "Wukong"; break;
                case 53: result = "Blitzcrank"; break;
                case 98: result = "Shen"; break;
                case 201: result = "Braum"; break;
                case 5: result = "Xin Zhao"; break;
                case 29: result = "Twitch"; break;
                case 11: result = "Master Yi"; break;
                case 44: result = "Taric"; break;
                case 32: result = "Amumu"; break;
                case 41: result = "Gangplank"; break;
                case 48: result = "Trundle"; break;
                case 38: result = "Kassadin"; break;
                case 161: result = "Vel'Koz"; break;
                case 143: result = "Zyra"; break;
                case 267: result = "Nami"; break;
                case 59: result = "Jarvan IV"; break;
                case 81: result = "Ezreal"; break;
                default: result = "New champion"; break;
            };
            return result;
        }
    }
}
